version: '1.0'
services:
  webservices:
   container_name: "PHP-SERVER"
   build: './build/php/'
   volumes:
     - .:/var/www/html
   ports:
    - 83:80 
   depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: quizz
      MYSQL_USER: de_user
      MYSQL_PASSWORD: password
    ports:
     - "3306:3306"